"""schema inicial: sobre_mim, projetos, projeto_imagens, habilidades

Revision ID: 23c07f8cb171
Revises: 
Create Date: 2026-08-10 23:24:18.850915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c07f8cb171'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('cor_fundo', sa.String(length=50), nullable=True),
    sa.Column('cor_texto', sa.String(length=50), nullable=True),
    sa.Column('destaque', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('descricao_curta', sa.String(length=255), nullable=False),
    sa.Column('descricao_longa', sa.Text(), nullable=True),
    sa.Column('imagem_capa', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('link_github', sa.String(length=255), nullable=True),
    sa.Column('link_deploy', sa.String(length=255), nullable=True),
    sa.Column('tipo_download', sa.String(length=50), nullable=True),
    sa.Column('destaque', sa.SmallInteger(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sobre_mim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo_principal', sa.String(length=255), nullable=False),
    sa.Column('subtitulo', sa.String(length=255), nullable=True),
    sa.Column('texto_home', sa.Text(), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('email_contato', sa.String(length=100), nullable=True),
    sa.Column('link_github', sa.String(length=255), nullable=True),
    sa.Column('link_linkedin', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projeto_imagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('imagem_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projeto_imagens')
    op.drop_table('sobre_mim')
    op.drop_table('projetos')
    op.drop_table('habilidades')
    # ### end Alembic commands ###
